apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vxrail-pod-allflash
  name: vxrail-pod-allflash
spec:
  nodeSelector:
    allflash: "yes"
  containers:
  - image: nginx
    name: vxrail-pod-allflash
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
