apiVersion: v1
data:
  password: dnhyYWlsMTIz
kind: Secret
metadata:
  name: password
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-secret
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    volumeMounts:
    - name: password
      mountPath: "/tmp"
      readOnly: true
  volumes:
  - name: password
    secret:
      secretName: password
