apiVersion: v1
kind: Pod
metadata:
  labels:
    run: vxrail-pod
  name: vxrail-pod
spec:
  nodeName: cluster1-worker3
  containers:
  - image: nginx
    name: vxrail-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
