apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-local-volume
spec:
  containers:
  - image: ubuntu
    name: ubuntu-with-local-vol
    volumeMounts:
    - mountPath: /local-vol
      name: ubuntu-vol
    command: ['sh','-c','sleep 300']
  volumes:
  - name: ubuntu-vol
    hostPath:
      # directory location on host
      path: /home/ubuntu
      # this field is optional
      type: Directory
