apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: default
spec:
  accessModes:
   - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: nfs-pv
  resources:
    requests:
      storage: 1Gi
