apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-env-secret
spec:
  containers:
  - image: ubuntu
    name: ubuntu-env-secret
    command: ['sh','-c','sleep 300']
    envFrom:
    - secretRef:
        name: app-location
