apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: pod-tester
    namespace: dev
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    verbs:
    - create
    - list
    - delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
