apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: pod-tester
    namespace: dev
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pod-tester
  subjects:
  - kind: ServiceAccount
    name: tester
    namespace: dev
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
